sudo: required
language: bash
script:
    - shellcheck ./test.sh
before_install:
  - sudo add-apt-repository -y ppa:danlipsitt/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y shellcheck
